[api]
# For agents on OTHER machines: replace localhost with the server's LAN/WiFi IP
# e.g. url = http://192.168.1.100:5000
# Run setup_agent.py to set this automatically.
url = http://localhost:5000
org_token = a8b6ea9bceae8b9cff9e63c2519d3e306453c1325306c64d

[agent]
device_id = 0be76b7f-0cd7-4931-a8aa-dfb00a03348c
agent_token = dfa390c3-392f-4be1-977d-2be107d6419aede5b60c90853687eef1e6ce744d12fc71ecbba65441671d10cc60404ee288ce
heartbeat_interval = 60
software_interval = 21600
version = 1.0.0

[logging]
level = INFO
file = rmm_agent.log

