"""add must_change_password to users

Revision ID: 93baa3927b0c
Revises: 2c8f1d3e9a4b
Create Date: 2026-06-03 19:58:32.139689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93baa3927b0c'
down_revision = '2c8f1d3e9a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_device_status'))

    with op.batch_alter_table('device_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_metrics_device_collected_at'))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_customer_online'))

    with op.batch_alter_table('patch_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patch_records_device_status'))

    with op.batch_alter_table('script_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_runs_device_status'))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_customer_status'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_customer_status'), ['customer_id', 'status'], unique=False)

    with op.batch_alter_table('script_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_runs_device_status'), ['device_id', 'status'], unique=False)

    with op.batch_alter_table('patch_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patch_records_device_status'), ['device_id', 'status'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_customer_online'), ['customer_id', 'is_online'], unique=False)

    with op.batch_alter_table('device_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_metrics_device_collected_at'), ['device_id', 'collected_at'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_device_status'), ['device_id', 'status'], unique=False)

    # ### end Alembic commands ###
