"""initial

Revision ID: d746c05420bd
Revises: 
Create Date: 2026-06-02 04:58:14.578257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd746c05420bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('primary_tech_id', sa.String(length=36), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registration_token_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_tech_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_slug'), ['slug'], unique=True)

    op.create_table('scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('os_target', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_groups_customer_id'), ['customer_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('per_device_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)

    op.create_table('network_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=True),
    sa.Column('scan_range', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('discovered_hosts', sa.JSON(), nullable=True),
    sa.Column('new_devices_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('device_group_id', sa.String(length=36), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('auto_create_ticket', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('device_group_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.Column('run_on_new_agents', sa.Boolean(), nullable=True),
    sa.Column('notification_emails', sa.JSON(), nullable=True),
    sa.Column('os_patch_config', sa.JSON(), nullable=True),
    sa.Column('software_patch_config', sa.JSON(), nullable=True),
    sa.Column('disk_config', sa.JSON(), nullable=True),
    sa.Column('maintenance_config', sa.JSON(), nullable=True),
    sa.Column('scripts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('os_build', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=100), nullable=True),
    sa.Column('public_ip', sa.String(length=45), nullable=True),
    sa.Column('hardware_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_customer_id'), ['customer_id'], unique=False)

    op.create_table('patch_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('device_group_id', sa.String(length=36), nullable=True),
    sa.Column('auto_approve_critical', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_security', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_service_packs', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_drivers', sa.Boolean(), nullable=True),
    sa.Column('reboot_behavior', sa.String(length=20), nullable=True),
    sa.Column('maintenance_window', sa.JSON(), nullable=True),
    sa.Column('winget_enabled', sa.Boolean(), nullable=True),
    sa.Column('choco_enabled', sa.Boolean(), nullable=True),
    sa.Column('excluded_software', sa.JSON(), nullable=True),
    sa.Column('software_bundles', sa.JSON(), nullable=True),
    sa.Column('upgrade_os', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('agent_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tokens_device_id'), ['device_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_device_id'), ['device_id'], unique=False)

    op.create_table('device_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=True),
    sa.Column('ram_pct', sa.Float(), nullable=True),
    sa.Column('ram_used_gb', sa.Float(), nullable=True),
    sa.Column('disk_pct', sa.Float(), nullable=True),
    sa.Column('disk_used_gb', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('network_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('network_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('battery_plugged', sa.Boolean(), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=True),
    sa.Column('top_processes', sa.JSON(), nullable=True),
    sa.Column('disks', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_metrics_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_metrics_device_id'), ['device_id'], unique=False)

    op.create_table('installed_software',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('install_date', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installed_software', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installed_software_device_id'), ['device_id'], unique=False)

    op.create_table('patch_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('patch_name', sa.String(length=500), nullable=False),
    sa.Column('kb_id', sa.String(length=50), nullable=True),
    sa.Column('patch_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('version_from', sa.String(length=255), nullable=True),
    sa.Column('version_to', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_by', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patch_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patch_records_device_id'), ['device_id'], unique=False)

    op.create_table('scheduled_task_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['automation_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_task_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_task_runs_profile_id'), ['profile_id'], unique=False)

    op.create_table('script_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('script_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_runs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_script_runs_script_id'), ['script_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_customer_id'), ['customer_id'], unique=False)

    op.create_table('ticket_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comments_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comments_ticket_id'))

    op.drop_table('ticket_comments')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_customer_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('script_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_runs_script_id'))
        batch_op.drop_index(batch_op.f('ix_script_runs_device_id'))

    op.drop_table('script_runs')
    with op.batch_alter_table('scheduled_task_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_task_runs_profile_id'))

    op.drop_table('scheduled_task_runs')
    with op.batch_alter_table('patch_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patch_records_device_id'))

    op.drop_table('patch_records')
    with op.batch_alter_table('installed_software', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installed_software_device_id'))

    op.drop_table('installed_software')
    with op.batch_alter_table('device_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_metrics_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_metrics_collected_at'))

    op.drop_table('device_metrics')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_device_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('agent_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tokens_device_id'))

    op.drop_table('agent_tokens')
    op.drop_table('patch_policies')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_customer_id'))

    op.drop_table('devices')
    op.drop_table('automation_profiles')
    op.drop_table('alert_rules')
    op.drop_table('reports')
    op.drop_table('network_scans')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('device_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_groups_customer_id'))

    op.drop_table('device_groups')
    op.drop_table('scripts')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_slug'))

    op.drop_table('customers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
